version: '3'

services:
  api:
    container_name: employee-system
    build: 
      context: .
      dockerfile: docker/Dockerfile 
    ports:
      - "9000:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
    networks:       
      - employee-system

  nginx:
    container_name: employee-nginx
    image: nginx:1.26
    ports:
      - "9966:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    networks:       
      - employee-system

  db:
    container_name: employee-system-mysql-compose
    image: mysql:8.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - "3366:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=employees-system
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root
    volumes:
      - employee-system:/var/lib/mysql
      - ./db/init-scripts/schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:       
      - employee-system

volumes:
  employee-system:

networks:
  employee-system: